// Generated by /vnpt_workflow_stitch2flutter — edit_contract
// Source: SRS OBM_edit_contract_srs.docx
// Endpoint: PUT http://10.168.6.37:9080/api/v1/contracts/{id}

class ContractDetailModel {
  final int? id;
  final int? owningUnitId;
  final int? opportunityId;
  final int? projectId;
  final int? customerId;
  final int? productServiceId;
  final String? regionCode;
  final String? businessField;
  final String? name;
  final String? contractNo;
  final String? typeCode;
  final String? statusCode;
  final String? managerName;
  final String? kmsLink;
  final String? signedDate;
  final String? acceptanceDate;
  final String? expiryDate;
  final int? durationMonths;
  final double? contractValue;
  final double? vnptValue;
  final double? itPercent;
  final double? vnptItValue;
  final String? bindingTerms;
  final String? note;

  const ContractDetailModel({
    this.id,
    this.owningUnitId,
    this.opportunityId,
    this.projectId,
    this.customerId,
    this.productServiceId,
    this.regionCode,
    this.businessField,
    this.name,
    this.contractNo,
    this.typeCode,
    this.statusCode,
    this.managerName,
    this.kmsLink,
    this.signedDate,
    this.acceptanceDate,
    this.expiryDate,
    this.durationMonths,
    this.contractValue,
    this.vnptValue,
    this.itPercent,
    this.vnptItValue,
    this.bindingTerms,
    this.note,
  });

  factory ContractDetailModel.fromJson(Map<String, dynamic> json) =>
      ContractDetailModel(
        id: json['id'] as int?,
        owningUnitId: json['owningUnitId'] as int?,
        opportunityId: json['opportunityId'] as int?,
        projectId: json['projectId'] as int?,
        customerId: json['customerId'] as int?,
        productServiceId: json['productServiceId'] as int?,
        regionCode: json['regionCode'] as String?,
        businessField: json['businessField'] as String?,
        name: json['name'] as String?,
        contractNo: json['contractNo'] as String?,
        typeCode: json['typeCode'] as String?,
        statusCode: json['statusCode'] as String?,
        managerName: json['managerName'] as String?,
        kmsLink: json['kmsLink'] as String?,
        signedDate: json['signedDate'] as String?,
        acceptanceDate: json['acceptanceDate'] as String?,
        expiryDate: json['expiryDate'] as String?,
        durationMonths: json['durationMonths'] as int?,
        contractValue: (json['contractValue'] as num?)?.toDouble(),
        vnptValue: (json['vnptValue'] as num?)?.toDouble(),
        itPercent: (json['itPercent'] as num?)?.toDouble(),
        vnptItValue: (json['vnptItValue'] as num?)?.toDouble(),
        bindingTerms: json['bindingTerms'] as String?,
        note: json['note'] as String?,
      );
}
