// Generated by /vnpt_workflow_stitch2flutter — add_contract
// Source: SRS OBM_add_contract_srs.docx + Postman OBM/AddContract
// Endpoint: POST http://10.168.6.37:9080/contracts

class AddContractRequest {
  final int? id;
  final int? owningUnitId;
  final int? opportunityId;
  final int? projectId;
  final int? customerId;
  final int? productServiceId;
  final String? regionCode;
  final String? businessField;
  final String? name;
  final String? contractNo;
  final String? typeCode;
  final String? statusCode;
  final String? managerName;
  final String? kmsLink;
  final String? signedDate;
  final String? acceptanceDate;
  final String? expiryDate;
  final int? durationMonths;
  final double? contractValue;
  final double? vnptValue;
  final double? itPercent;
  final double? vnptItValue;
  final String? bindingTerms;
  final String? note;

  const AddContractRequest({
    this.id,
    this.owningUnitId,
    this.opportunityId,
    this.projectId,
    this.customerId,
    this.productServiceId,
    this.regionCode,
    this.businessField,
    this.name,
    this.contractNo,
    this.typeCode,
    this.statusCode,
    this.managerName,
    this.kmsLink,
    this.signedDate,
    this.acceptanceDate,
    this.expiryDate,
    this.durationMonths,
    this.contractValue,
    this.vnptValue,
    this.itPercent,
    this.vnptItValue,
    this.bindingTerms,
    this.note,
  });

  Map<String, dynamic> toJson() => {
        if (id != null) 'id': id,
        if (owningUnitId != null) 'owningUnitId': owningUnitId,
        if (opportunityId != null) 'opportunityId': opportunityId,
        if (projectId != null) 'projectId': projectId,
        if (customerId != null) 'customerId': customerId,
        if (productServiceId != null) 'productServiceId': productServiceId,
        if (regionCode != null) 'regionCode': regionCode,
        if (businessField != null) 'businessField': businessField,
        if (name != null) 'name': name,
        if (contractNo != null) 'contractNo': contractNo,
        if (typeCode != null) 'typeCode': typeCode,
        if (statusCode != null) 'statusCode': statusCode,
        if (managerName != null) 'managerName': managerName,
        if (kmsLink != null) 'kmsLink': kmsLink,
        if (signedDate != null) 'signedDate': signedDate,
        if (acceptanceDate != null) 'acceptanceDate': acceptanceDate,
        if (expiryDate != null) 'expiryDate': expiryDate,
        if (durationMonths != null) 'durationMonths': durationMonths,
        if (contractValue != null) 'contractValue': contractValue,
        if (vnptValue != null) 'vnptValue': vnptValue,
        if (itPercent != null) 'itPercent': itPercent,
        if (vnptItValue != null) 'vnptItValue': vnptItValue,
        if (bindingTerms != null) 'bindingTerms': bindingTerms,
        if (note != null) 'note': note,
      };
}

// ─── Filter Options (3.1) ────────────────────────────────────────────
class FilterOptionsResponse {
  final List<DeptLineModel> lines;
  final List<DeptLineModel> depts;
  final List<ProductRefModel> products;

  const FilterOptionsResponse({
    this.lines = const [],
    this.depts = const [],
    this.products = const [],
  });

  factory FilterOptionsResponse.fromJson(Map<String, dynamic> json) {
    return FilterOptionsResponse(
      lines: (json['lines'] as List?)
              ?.map((e) => DeptLineModel.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
      depts: (json['depts'] as List?)
              ?.map((e) => DeptLineModel.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
      products: (json['products'] as List?)
              ?.map((e) => ProductRefModel.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
    );
  }
}

class DeptLineModel {
  final int? id;
  final String? name;
  final int? parentId;

  const DeptLineModel({this.id, this.name, this.parentId});

  factory DeptLineModel.fromJson(Map<String, dynamic> json) =>
      DeptLineModel(
        id: json['id'] as int?,
        name: json['name'] as String?,
        parentId: json['parentId'] as int?,
      );
}

class ProductRefModel {
  final int? id;
  final String? name;
  final String? lineName;

  const ProductRefModel({this.id, this.name, this.lineName});

  factory ProductRefModel.fromJson(Map<String, dynamic> json) =>
      ProductRefModel(
        id: json['id'] as int?,
        name: json['name'] as String?,
        lineName: json['lineName'] as String?,
      );
}

// ─── Opportunities (3.2) ─────────────────────────────────────────────
class OpportunityModel {
  final int? id;
  final String? code;
  final String? name;
  final String? customerName;
  final String? owningUnitName;
  final String? fieldLabel;
  final String? statusLabel;

  const OpportunityModel({
    this.id,
    this.code,
    this.name,
    this.customerName,
    this.owningUnitName,
    this.fieldLabel,
    this.statusLabel,
  });

  factory OpportunityModel.fromJson(Map<String, dynamic> json) =>
      OpportunityModel(
        id: json['id'] as int?,
        code: json['code'] as String?,
        name: json['name'] as String?,
        customerName: json['customerName'] as String?,
        owningUnitName: json['owningUnitName'] as String?,
        fieldLabel: json['fieldLabel'] as String?,
        statusLabel: json['statusLabel'] as String?,
      );
}

class OpportunityResponse {
  final List<OpportunityModel> content;

  const OpportunityResponse({this.content = const []});

  factory OpportunityResponse.fromJson(Map<String, dynamic> json) =>
      OpportunityResponse(
        content: (json['content'] as List?)
                ?.map((e) => OpportunityModel.fromJson(e as Map<String, dynamic>))
                .toList() ??
            const [],
      );
}

// ─── Projects (3.3) ─────────────────────────────────────────────────
class ProjectRefModel {
  final int? id;
  final String? code;
  final String? name;
  final String? customerName;
  final String? owningUnitName;
  final int? opportunityId;
  final String? opportunityCode;

  const ProjectRefModel({
    this.id,
    this.code,
    this.name,
    this.customerName,
    this.owningUnitName,
    this.opportunityId,
    this.opportunityCode,
  });

  factory ProjectRefModel.fromJson(Map<String, dynamic> json) =>
      ProjectRefModel(
        id: json['id'] as int?,
        code: json['code'] as String?,
        name: json['name'] as String?,
        customerName: json['customerName'] as String?,
        owningUnitName: json['owningUnitName'] as String?,
        opportunityId: json['opportunityId'] as int?,
        opportunityCode: json['opportunityCode'] as String?,
      );
}

class ProjectRefResponse {
  final List<ProjectRefModel> content;

  const ProjectRefResponse({this.content = const []});

  factory ProjectRefResponse.fromJson(Map<String, dynamic> json) =>
      ProjectRefResponse(
        content: (json['content'] as List?)
                ?.map((e) => ProjectRefModel.fromJson(e as Map<String, dynamic>))
                .toList() ??
            const [],
      );
}

// ─── Customers (3.4) ────────────────────────────────────────────────
class CustomerModel {
  final int? id;
  final String? code;
  final String? name;
  final String? province;

  const CustomerModel({
    this.id,
    this.code,
    this.name,
    this.province,
  });

  factory CustomerModel.fromJson(Map<String, dynamic> json) => CustomerModel(
        id: json['id'] as int?,
        code: json['code'] as String?,
        name: json['name'] as String?,
        province: json['province'] as String?,
      );
}

class CustomerResponse {
  final List<CustomerModel> content;

  const CustomerResponse({this.content = const []});

  factory CustomerResponse.fromJson(Map<String, dynamic> json) =>
      CustomerResponse(
        content: (json['content'] as List?)
                ?.map((e) => CustomerModel.fromJson(e as Map<String, dynamic>))
                .toList() ??
            const [],
      );
}

// ─── Product Services (3.5) ─────────────────────────────────────────
class ProductServiceModel {
  final int? id;
  final String? code;
  final String? name;
  final String? categoryName;
  final String? serviceTypeLabel;
  final String? lineUnitName;

  const ProductServiceModel({
    this.id,
    this.code,
    this.name,
    this.categoryName,
    this.serviceTypeLabel,
    this.lineUnitName,
  });

  factory ProductServiceModel.fromJson(Map<String, dynamic> json) =>
      ProductServiceModel(
        id: json['id'] as int?,
        code: json['code'] as String?,
        name: json['name'] as String?,
        categoryName: json['categoryName'] as String?,
        serviceTypeLabel: json['serviceTypeLabel'] as String?,
        lineUnitName: json['lineUnitName'] as String?,
      );
}

class ProductServiceResponse {
  final List<ProductServiceModel> content;

  const ProductServiceResponse({this.content = const []});

  factory ProductServiceResponse.fromJson(Map<String, dynamic> json) =>
      ProductServiceResponse(
        content: (json['content'] as List?)
                ?.map((e) => ProductServiceModel.fromJson(e as Map<String, dynamic>))
                .toList() ??
            const [],
      );
}

// ─── Static Config (Static Enums) ────────────────────────────────────
class FieldRef {
  final String code;
  final String label;
  final String badge;
  const FieldRef({required this.code, required this.label, required this.badge});
}

class RegionRef {
  final String code;
  final String label;
  const RegionRef({required this.code, required this.label});
}

class ContractTypeRef {
  final String code;
  final String label;
  const ContractTypeRef({required this.code, required this.label});
}

class ContractStatusRef {
  final String code;
  final String label;
  final String badge;
  const ContractStatusRef(
      {required this.code, required this.label, required this.badge});
}

class AddContractConfig {
  static const List<RegionRef> regions = [
    RegionRef(code: 'ITKV1', label: 'ITKV1'),
    RegionRef(code: 'ITKV2', label: 'ITKV2'),
    RegionRef(code: 'ITKV3', label: 'ITKV3'),
    RegionRef(code: 'ITKV4', label: 'ITKV4'),
    RegionRef(code: 'ITKV5', label: 'ITKV5'),
    RegionRef(code: 'HCMC', label: 'TP. Hồ Chí Minh'),
    RegionRef(code: 'OVERSEAS', label: 'Quốc tế'),
    RegionRef(code: 'NGHEAN', label: 'Nghệ An'),
    RegionRef(code: 'DONGTHAP', label: 'Đồng Tháp'),
    RegionRef(code: 'DONGNAI', label: 'Đồng Nai'),
    RegionRef(code: 'HANOI', label: 'Hà Nội'),
  ];

  static const List<FieldRef> projectFields = [
    FieldRef(code: 'EGOV', label: 'Chính phủ điện tử', badge: 'bg-secondary'),
    FieldRef(code: 'HEALTH', label: 'Y tế', badge: 'bg-primary'),
    FieldRef(code: 'EDUCATION', label: 'Giáo dục', badge: 'bg-warning'),
    FieldRef(code: 'FINANCE', label: 'Tài chính - Ngân hàng', badge: 'bg-success'),
    FieldRef(code: 'TELECOM', label: 'Viễn thông', badge: 'bg-secondary'),
    FieldRef(code: 'ENTERPRISE', label: 'Doanh nghiệp', badge: 'bg-primary'),
    FieldRef(code: 'TRANSPORT', label: 'Giao thông', badge: 'bg-warning'),
    FieldRef(code: 'AGRICULTURE', label: 'Nông nghiệp', badge: 'bg-success'),
    FieldRef(code: 'OTHER', label: 'Khác', badge: 'bg-secondary'),
  ];

  static const List<ContractTypeRef> contractTypes = [
    ContractTypeRef(code: 'LEASE', label: 'Cho thuê dịch vụ'),
    ContractTypeRef(code: 'DEPLOY', label: 'Triển khai / Mua bán'),
    ContractTypeRef(code: 'MAINTENANCE', label: 'Bảo hành / Bảo trì'),
    ContractTypeRef(code: 'UPGRADE', label: 'Nâng cấp / Mở rộng'),
    ContractTypeRef(code: 'OTHER', label: 'Khác'),
  ];

  static const List<ContractStatusRef> contractStatuses = [
    ContractStatusRef(code: 'DRAFT', label: 'Dự thảo', badge: '#6C757D'),
    ContractStatusRef(code: 'SIGNED', label: 'Đã ký', badge: '#0A6FFD'),
    ContractStatusRef(code: 'ACTIVE', label: 'Đang hiệu lực', badge: '#198755'),
    ContractStatusRef(code: 'EXPIRING', label: 'Sắp hết hạn', badge: '#FFC106'),
    ContractStatusRef(code: 'EXPIRED', label: 'Hết hạn', badge: '#212529'),
    ContractStatusRef(code: 'LIQUIDATED', label: 'Đã thanh lý', badge: '#10CAF0'),
  ];
}